application:
  name: ${spring.application.name}
  version: ${spring.application.version}

spring:
  application:
    name: my-api
    version: "@version@"
  profiles:
    active: "${env:PROD}"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration

  mvc:
    app:
      async:
        request-timeout: 10000
      servlet:
        path: /api
      static-path-pattern: /**
    one:
      async:
        request-timeout: 10000
      servlet:
        path: /api/one
      static-path-pattern: /**
    two:
      async:
        request-timeout: 10000
      servlet:
        path: /api/two
      static-path-pattern: /**

## logging level group
# https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-custom-log-groups
logging:
  level:
    web: WARN
    sql: WARN


# Metrics.
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Web.
server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-threads: 400
